<script>
  let { data } = $props();
  const { incident, updates, reportCount, duration, impact, correlatedIncidents } = data;

  const api = incident.apis;
  const isResolved = incident.status === 'resolved';

  function formatTime(iso) {
    return new Date(iso).toLocaleString('en-US', {
      month: 'short', day: 'numeric', year: 'numeric',
      hour: '2-digit', minute: '2-digit', timeZoneName: 'short',
    });
  }

  function severityBadge(sev) {
    if (sev === 'critical') return 'sev-critical';
    if (sev === 'major') return 'sev-major';
    return 'sev-minor';
  }

  function statusIcon(status) {
    const map = { investigating: 'magnifying glass', identified: 'target', monitoring: 'eye', resolved: 'check' };
    return map[status] || status;
  }
</script>

<svelte:head>
  <title>Postmortem: {incident.title} — {api.name} — APIdown.net</title>
  <meta name="description" content="Incident postmortem for {api.name}: {incident.title}. Duration: {duration.formatted}. Error rate: {impact.errorRate}%. Auto-generated by APIdown.net." />
  <link rel="canonical" href="https://apidown.net/incidents/{incident.id}/postmortem" />
  <meta property="og:title" content="Postmortem: {incident.title}" />
  <meta property="og:description" content="{api.name} incident lasting {duration.formatted} with {impact.errorRate}% error rate. Full timeline and impact analysis." />
</svelte:head>

<div class="postmortem">
  <nav class="breadcrumb" aria-label="Breadcrumb">
    <a href="/">Home</a> <span>/</span>
    <a href="/incidents">Incidents</a> <span>/</span>
    <a href="/incidents/{incident.id}">{incident.title}</a> <span>/</span>
    <span>Postmortem</span>
  </nav>

  <!-- Header -->
  <header class="pm-header">
    <div class="pm-header-top">
      <span class="pm-sev {severityBadge(incident.severity)}">{incident.severity}</span>
      <span class="pm-status pm-status-{incident.status}">{incident.status}</span>
    </div>
    <h1>{incident.title}</h1>
    <p class="pm-api">
      {#if api.logo_url}
        <img src={api.logo_url} alt="" width="20" height="20" class="pm-api-logo" />
      {/if}
      <a href="/api/{api.slug}">{api.name}</a>
    </p>
  </header>

  <!-- Summary Cards -->
  <div class="summary-grid">
    <div class="summary-card">
      <span class="summary-label">Duration</span>
      <span class="summary-value">{duration.formatted}</span>
    </div>
    <div class="summary-card">
      <span class="summary-label">Error Rate</span>
      <span class="summary-value">{impact.errorRate}%</span>
    </div>
    <div class="summary-card">
      <span class="summary-label">Peak P95 Latency</span>
      <span class="summary-value">{impact.peakP95 > 0 ? impact.peakP95 + 'ms' : 'N/A'}</span>
    </div>
    <div class="summary-card">
      <span class="summary-label">Total Signals</span>
      <span class="summary-value">{impact.totalSignals.toLocaleString()}</span>
    </div>
    <div class="summary-card">
      <span class="summary-label">Affected Regions</span>
      <span class="summary-value">{impact.affectedRegions.length > 0 ? impact.affectedRegions.join(', ') : 'N/A'}</span>
    </div>
    <div class="summary-card">
      <span class="summary-label">User Reports</span>
      <span class="summary-value">{reportCount}</span>
    </div>
  </div>

  <!-- Timeline -->
  <section class="timeline-section">
    <h2>Timeline</h2>
    <div class="timeline">
      <div class="tl-entry">
        <div class="tl-dot tl-dot-start"></div>
        <div class="tl-content">
          <span class="tl-time">{formatTime(incident.started_at)}</span>
          <span class="tl-label">Incident detected</span>
          {#if incident.auto_created}
            <span class="tl-tag">Auto-detected by anomaly engine</span>
          {:else}
            <span class="tl-tag">Manually reported</span>
          {/if}
        </div>
      </div>

      {#each updates as update (update.id)}
        <div class="tl-entry">
          <div class="tl-dot tl-dot-{update.status}"></div>
          <div class="tl-content">
            <span class="tl-time">{formatTime(update.created_at)}</span>
            <span class="tl-label tl-label-{update.status}">{update.status}</span>
            {#if update.message}
              <p class="tl-message">{update.message}</p>
            {/if}
          </div>
        </div>
      {/each}

      {#if isResolved && incident.resolved_at}
        <div class="tl-entry">
          <div class="tl-dot tl-dot-resolved"></div>
          <div class="tl-content">
            <span class="tl-time">{formatTime(incident.resolved_at)}</span>
            <span class="tl-label tl-label-resolved">Resolved</span>
          </div>
        </div>
      {/if}
    </div>
  </section>

  <!-- Correlated Incidents -->
  {#if correlatedIncidents.length > 0}
    <section class="correlated-section">
      <h2>Correlated Incidents</h2>
      <p class="correlated-desc">Other APIs that experienced issues during the same time window (±15 minutes).</p>
      <div class="correlated-list">
        {#each correlatedIncidents as ci (ci.id)}
          <a href="/incidents/{ci.id}" class="correlated-card">
            <span class="cor-sev {severityBadge(ci.severity)}">{ci.severity}</span>
            <span class="cor-api">{ci.apiName}</span>
            <span class="cor-title">{ci.title}</span>
            <span class="cor-status cor-status-{ci.status}">{ci.status}</span>
          </a>
        {/each}
      </div>
    </section>
  {/if}

  <!-- Footer -->
  <div class="pm-footer">
    <p>This postmortem was auto-generated from crowd-sourced monitoring data by <a href="https://apidown.net">APIdown.net</a>.</p>
    <p class="pm-footer-date">Generated {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
  </div>
</div>

<style>
  .postmortem {
    max-width: 780px;
    margin: 0 auto;
    padding: 1.5rem 1rem;
  }

  .breadcrumb {
    font-size: 0.8rem;
    color: var(--color-text-muted);
    margin-bottom: 1.5rem;
  }

  .breadcrumb a { color: var(--color-text-muted); text-decoration: none; }
  .breadcrumb a:hover { color: var(--color-primary); }
  .breadcrumb span { margin: 0 0.3rem; }

  /* Header */
  .pm-header {
    margin-bottom: 1.5rem;
  }

  .pm-header-top {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    margin-bottom: 0.5rem;
  }

  .pm-sev {
    font-size: 0.65rem;
    font-weight: 700;
    text-transform: uppercase;
    padding: 0.15rem 0.5rem;
    border-radius: 4px;
  }

  .sev-critical { background: rgba(239, 68, 68, 0.15); color: #ef4444; }
  .sev-major { background: rgba(245, 158, 11, 0.15); color: #f59e0b; }
  .sev-minor { background: rgba(74, 222, 128, 0.15); color: #4ade80; }

  .pm-status {
    font-size: 0.75rem;
    font-weight: 600;
    text-transform: capitalize;
  }

  .pm-status-resolved { color: var(--color-operational); }
  .pm-status-investigating, .pm-status-identified { color: var(--color-degraded); }
  .pm-status-monitoring { color: var(--color-primary); }

  .pm-header h1 {
    font-size: 1.5rem;
    font-weight: 700;
    margin-bottom: 0.4rem;
  }

  .pm-api {
    display: flex;
    align-items: center;
    gap: 0.4rem;
  }

  .pm-api-logo { width: 20px; height: 20px; border-radius: 3px; }
  .pm-api a { color: var(--color-primary); text-decoration: none; font-weight: 500; }
  .pm-api a:hover { text-decoration: underline; }

  /* Summary Grid */
  .summary-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
    gap: 0.75rem;
    margin-bottom: 2rem;
  }

  .summary-card {
    background: var(--color-surface);
    border: 1px solid var(--color-border);
    border-radius: 8px;
    padding: 0.75rem;
    text-align: center;
  }

  .summary-label {
    display: block;
    font-size: 0.7rem;
    color: var(--color-text-muted);
    text-transform: uppercase;
    letter-spacing: 0.03em;
    margin-bottom: 0.25rem;
  }

  .summary-value {
    font-size: 1.1rem;
    font-weight: 700;
  }

  /* Timeline */
  .timeline-section {
    margin-bottom: 2rem;
  }

  .timeline-section h2 {
    font-size: 1.1rem;
    font-weight: 700;
    margin-bottom: 1rem;
  }

  .timeline {
    position: relative;
    padding-left: 2rem;
  }

  .timeline::before {
    content: '';
    position: absolute;
    left: 7px;
    top: 0;
    bottom: 0;
    width: 2px;
    background: var(--color-border);
  }

  .tl-entry {
    position: relative;
    margin-bottom: 1.25rem;
  }

  .tl-entry:last-child { margin-bottom: 0; }

  .tl-dot {
    position: absolute;
    left: -2rem;
    top: 0.15rem;
    width: 12px;
    height: 12px;
    border-radius: 50%;
    border: 2px solid var(--color-border);
    background: var(--color-bg);
    z-index: 1;
  }

  .tl-dot-start { border-color: var(--color-down); background: var(--color-down); }
  .tl-dot-investigating { border-color: var(--color-degraded); }
  .tl-dot-identified { border-color: var(--color-degraded); background: var(--color-degraded); }
  .tl-dot-monitoring { border-color: var(--color-primary); }
  .tl-dot-resolved { border-color: var(--color-operational); background: var(--color-operational); }

  .tl-content {
    display: flex;
    flex-direction: column;
    gap: 0.15rem;
  }

  .tl-time {
    font-size: 0.75rem;
    color: var(--color-text-muted);
  }

  .tl-label {
    font-size: 0.85rem;
    font-weight: 600;
    text-transform: capitalize;
  }

  .tl-label-investigating { color: var(--color-degraded); }
  .tl-label-identified { color: var(--color-degraded); }
  .tl-label-monitoring { color: var(--color-primary); }
  .tl-label-resolved { color: var(--color-operational); }

  .tl-tag {
    font-size: 0.7rem;
    color: var(--color-text-muted);
    font-style: italic;
  }

  .tl-message {
    font-size: 0.85rem;
    color: var(--color-text);
    line-height: 1.4;
    margin-top: 0.15rem;
  }

  /* Correlated */
  .correlated-section {
    margin-bottom: 2rem;
  }

  .correlated-section h2 {
    font-size: 1.1rem;
    font-weight: 700;
    margin-bottom: 0.25rem;
  }

  .correlated-desc {
    font-size: 0.85rem;
    color: var(--color-text-muted);
    margin-bottom: 0.75rem;
  }

  .correlated-list {
    display: flex;
    flex-direction: column;
    gap: 0.4rem;
  }

  .correlated-card {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.6rem 0.75rem;
    background: var(--color-surface);
    border: 1px solid var(--color-border);
    border-radius: 6px;
    text-decoration: none;
    color: var(--color-text);
    font-size: 0.85rem;
    transition: border-color 0.15s;
  }

  .correlated-card:hover { border-color: var(--color-primary); }

  .cor-sev {
    font-size: 0.6rem;
    font-weight: 700;
    text-transform: uppercase;
    padding: 0.1rem 0.35rem;
    border-radius: 3px;
    flex-shrink: 0;
  }

  .cor-api { font-weight: 600; flex-shrink: 0; }
  .cor-title { flex: 1; color: var(--color-text-muted); }
  .cor-status { font-weight: 600; text-transform: capitalize; font-size: 0.8rem; flex-shrink: 0; }
  .cor-status-resolved { color: var(--color-operational); }
  .cor-status-investigating { color: var(--color-degraded); }

  /* Footer */
  .pm-footer {
    text-align: center;
    padding-top: 1.5rem;
    border-top: 1px solid var(--color-border);
    font-size: 0.8rem;
    color: var(--color-text-muted);
  }

  .pm-footer a { color: var(--color-primary); }

  .pm-footer-date {
    font-size: 0.75rem;
    margin-top: 0.25rem;
    opacity: 0.7;
  }

  @media (max-width: 640px) {
    .pm-header h1 { font-size: 1.2rem; }
    .summary-grid { grid-template-columns: repeat(2, 1fr); }
    .correlated-card { flex-wrap: wrap; }
  }
</style>
